version: "3"   

volumes:
        postgres_data:

services:
        flask-app:
                build: app/.
                container_name: flask_app
                restart: always
                environment:
                        SECRET_CSRF_KEY: ${SECRET_CSRF_KEY}
                        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
                        POSTGRES_USER: ${POSTGRES_USER}
                        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                        POSTGRES_DB: ${POSTGRES_DB}
                depends_on:
                        - redis
                        - postgresql
                ports:
                        - 5000:5000
                network_mode: host
                command: bash -c "flask run -h 0.0.0.0"
        redis:
                image: redis:alpine
                container_name: redis
                ports:
                        - 6379:6379
                network_mode: host
        postgresql:
                image: postgres
                environment:
                        - POSTGRES_USER=${POSTGRES_USER}
                        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
                        - POSTGRES_DB=${POSTGRES_DB}
                volumes:
                        - postgres_data:/var/lib/postgresql/data/
                ports:
                        - 5432:5432
                expose:
                        - '5432'
