version: "3"   

volumes:
        postgres_data:

services:
        flask-app:
                build: app/.
                container_name: app
                restart: always
                environment:
                        SECRET_CSRF_KEY: ${SECRET_CSRF_KEY}
                        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
                        POSTGRES_USER: ${POSTGRES_USER}
                        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
                        POSTGRES_DB: ${POSTGRES_DB}
                        MAIL_USERNAME: ${MAIL_USERNAME}
                        MAIL_PASSWORD: ${MAIL_PASSWORD}
                depends_on:
                        - redis
                        - postgresql
                expose:
                        - "5000"
                command: bash -c "gunicorn --bind 0.0.0.0:5000 main:app --reload"
                network_mode: host
        redis:
                image: redis:alpine
                container_name: redis
                restart: always
                ports:
                        - 6379:6379
                network_mode: host
        postgresql:
                image: postgres
                container_name: postgres
                restart: always
                environment:
                        - POSTGRES_USER=${POSTGRES_USER}
                        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
                        - POSTGRES_DB=${POSTGRES_DB}
                volumes:
                        - postgres_data:/var/lib/postgresql/data/
                ports:
                        - 5432:5432
                expose:
                        - '5432'
        nginx:
                build: ./nginx
                container_name: nginx
                restart: always
                ports:
                        - 80:80
                network_mode: host
