version: "3"   

volumes:
        mysql_db_data_container:

services:
        mysql:
                image: mysql
                container_name: mysql_db
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                environment:
                        MYSQL_DATABASE: 'shelper'
                        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
                ports:
                        - 3306:3306
                expose:
                        - '3306'
                volumes:
                        - 'mysql_db_data_container:/var/lib/mysql'
        flask-app:
                build: app/.
                container_name: flask_app
                restart: always
                environment:
                        SECRET_CSRF_KEY: ${SECRET_CSRF_KEY}
                        DB_PASSWORD: ${DB_PASSWORD}
                        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
                depends_on:
                        - mysql
                        - redis
                ports:
                        - 5000:5000
                network_mode: host
                command: bash -c "flask run"
        redis:
                image: redis:alpine
                container_name: redis
                ports:
                        - 6379:6379
                network_mode: host
