version: "3"   

services:
        flask-app:
                build: .
                restart: always
                ports:
                        - 5000:5000
                network_mode: host
                command: bash -c "flask run"
